const express =require("express")
const app=express()
require("dotenv").config()
const commonRouter=require("./routes/common")
const adminRouter=require("./routes/admin")
const studentRouter=require("./routes/student")
const auth=require("./utils/auth")
const allowedRoles=require("./utils/allowedRoles")
const cors = require('cors')
app.use(express.json())
app.use(cors())
app.use(commonRouter)
app.use("/admin",auth,allowedRoles("admin"),adminRouter)
app.use("/student",auth,allowedRoles("student"),studentRouter)
app.listen(4000,()=>{
    console.log("server is running on port 4000")
})